# Generated by Django 4.2.1 on 2023-05-23 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawData',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                (
                    'deleted_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                ('hd5_url', models.TextField()),
                (
                    'video_url',
                    models.TextField(blank=True, default=None, null=True),
                ),
                (
                    'eye',
                    models.IntegerField(
                        blank=True,
                        choices=[(0, 'left'), (1, 'right')],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    'mode',
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (0, 'Fixation mode'),
                            (1, 'Saccade tracking mode 3'),
                        ],
                        default=None,
                        null=True,
                    ),
                ),
                (
                    'proceed_at',
                    models.DateTimeField(blank=True, default=None, null=True),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
